#pragma once

// #define USER_COUNT 1000
// #define MIN_BALANCE 100
// #define MAX_BALANCE 1000000
// #define TRANSACTION_COUNT 10000
// #define MIN_TRANSACTION 100
// #define MAX_TRANSACTION 100000
// #define TRANSACTIONS_IN_BLOCK 100
// #define MINER_COUNT 12

#define DIFFICULTY_TARGET 5
#define VERSION 1

// more output
#define BE_VERBOSE
#define VERBOSE_ADD
#define VERBOSE_GENERATION
#define VERBOSE_MERKLE
#define VERBOSE_REMOVE
#define VERBOSE_MINING
#define USER_COUNT 5
#define MIN_BALANCE 100
#define MAX_BALANCE 1000
#define TRANSACTION_COUNT 10
#define MIN_TRANSACTION 42
#define MAX_TRANSACTION 420
#define TRANSACTIONS_IN_BLOCK 3
#define MINER_COUNT 1
